import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Course Learning",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/neural.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          logoImageUrl: "/icons/neural.png",
          termsPageUrl: "/",
          animations: true,
        },
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <div className="h-screen pt-[60px]">
            {children}
            <Toaster
              toastOptions={{
                className: "",
                style: {
                  marginTop: "60px",
                },
              }}
            />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
